# Generated by Django 3.2 on 2022-10-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_game_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='game', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.game'),
        ),
    ]
